hello/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include('home.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path

from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name="register"),
    path('homeworks/', views.homework, name="homeworks"),
    path('homework/add', views.homework_add, name="homework_add"),
    path('homework/edit/<int:id>', views.homework_edit, name="homework_edit"),
    path('homework/delete/<int:id>',views.homework_delete, name="homework_delete" ), 
    path('homewor/done/<int:id>', views.homework_done, name="homework_done")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Homework(models.Model):
    title = models.CharField(max_length=255, null=False)
    content = models.TextField(null=True, blank=True)
    deadline = models.DateField(null= True, blank= True)
    created_date = models.DateTimeField(null=True, blank=True)
    created_user = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.DO_NOTHING)
    done = models.BooleanField(default=False)
    image = models.ImageField(null=True, blank=True, max_length=255, upload_to='uploads/')
    lesson = models.ForeignKey('Lesson', null=True, blank=True, on_delete=models.DO_NOTHING)

class Lesson(models.Model):
    name = models.CharField(max_length=120, null=True, blank=True)

    def __str__(self):
        return self.name

home/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from .models import Homework


class NewUserForm(UserCreationForm):
    username = forms.CharField(
        label='Username',
        widget = forms.TextInput(attrs={
            'class': 'form-control'
        })
    )
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control'
        })
    )
    password2 = forms.CharField(
        label='Password2',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control'
        })
    )


class loginForm(AuthenticationForm):
    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(attrs={
                'class': 'form-control'
        }) 
    )
    password = forms.CharField(
        label ='Password',
        widget= forms.PasswordInput(attrs={
                'class': 'form-control'
        })
    )


class HomeWorkForm(forms.ModelForm):
    class Meta:
        model = Homework
        fields = ('title', 'content', 'deadline', 'image', 'lesson')
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "content":forms.Textarea(attrs={"class": "form-control"}),
            "deadline":forms.DateInput(attrs={"class": "form-control", "type":"date"}),
            "image": forms.ClearableFileInput(),
            "lesson": forms.Select(attrs={"class": "form-control"})
        }
        
        

home/views.py
import datetime
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .models import Homework
from .forms import NewUserForm, loginForm, HomeWorkForm
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator

def index(request):
    form = loginForm()
    message= ""
    user= request.user
    if request.method == "POST":
        form = loginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                message = "login success"
            else:
                message = "invalid username or password"
        else:
            message = "invalid username or password"
    
    return render(request, "home.html", {'form': form, 'message': message, 'user' : user })

def register(request):
    form = NewUserForm()
    message = ""
    if request.method == "POST":
        form = loginForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data.get("username")
            message = "Register succesfull"
    return render(request, "register.html", {'form': form, 'message': message})


def homework(request):
    home_works = Homework.objects.all()
    return render(request, "homework.html", {'homeworks': home_works})


def homeworks(request):
    home_works = Homework.objects.filter(
        created_user=request.user).order_by("id")
    paginator = Paginator(home_works, 2)
    page_number = request.GET.get("page")
    homework_page = paginator.get_page(page_number)
    return render(request, 'homework.html', {
        'homeworks' : homework_page,
    })


def homework_add(request):
    form = HomeWorkForm()
    message = ""
    if request.method == "POST":
        form = HomeWorkForm(request.POST, request.FILES)
        if form.is_valid():
            homework = form.save(commit=False)
            homework.created_user = request.user
            homework.created_date = datetime.datetime.now()
            homework.save()

            message = "Homework created succesfully"

    return render(request, 'homework.add.html', {'form': form, 'message': message})
            

def logout_view(request):
    logout(request)
    return redirect("index")


def homework_edit(request, id):
    homework = Homework.objects.get(id=id)
    form = HomeWorkForm(instance=homework)
    message=""
    if request.method == 'POST':
        form = HomeWorkForm(instance=homework, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            message = "Homework succesfully edited"
    return render(request, 'homework.add.html', {
        'form': form,
        'message': message
    })


def homework_delete(request, id):
    homework = Homework.objects.filter(
        created_user=request.user
    ).filter(id=id)
    homework.delete()
    return redirect("homeworks")


def homework_done(request, id):
    done = request.GET.get('done',False)
    homework = Homework.objects.get(id=id)
    homework.done = done
    homework.save()
    return redirect('homeworks')

hello/templates/base.html
<html>
    <head>
        <meta charset="utf-8">
           <meta name="viewport" content="width=device-width, initial-scale=1">
           <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous"> <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Homework-to do list</title>
    </head>
    <body>
        <div class="container">
            <ul class="nav bg-info">
                <li class="nav-item">
                    <a class="nav-link link-light" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light" href="/register">Register</a>
                </li>
                {% if user is not None and user.is_anonymous == False %}
                <li class="nav-item">
                    <a class="nav-link link-light" href="/homeworks">Homeworks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light" href="/homework/add">Add homework</a>
                </li>
                {% endif %}
            </ul>
                
        {% block content %}     
        {% endblock %}  
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
  
    </body>
</html>

hello/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-xl-5 col-lg-6 col-md-10 col-sm-12 mx-auto mt-5">
        {% if user is None or user.is_anonymous == True %}
            <h2> Нэвтрэх </h2>
            {% if message != "" %}
                <p class="alert alert danger"> {{ message }}</p>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="card body">
                    <div class="form group">
                        <label for="id_username">хэрэглэгчийн нэр</label>
                        {{ form.username }}
                        {{ form.username.errors }}
                    </div>
                    <div class="form-group">
                        <label for="id_password">Нууц үг</label>
                        {{ form.password }}
                        {{ form.password.errors}}
                    </div>
                    <div class="text-center">
                        <br><button class="btn btn-primary">Нэвтрэх</button>
                    </div>
                </div>
            </form>
        {% else %}
            welcome {{ user.username}}.
            <a href="{% url 'logout' %}">logout</a>
        {% endif %}
    </div>
</div>
{% endblock %}

hello/templates/homework.add.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-xl-5 col-lg-6 col-md-10 col-sm-12 mx-auto mt-5">
        <h2>Add homework</h2>
        {% if message != '' %}
            <p class="alert alert-success">{{message}}</p>
        {% endif %}
        <form method="post" novalidate enctype="multipart/form-data">
            {% csrf_token %}      
            <div class="card-body">
                <div class="form-group">
                    <label for="id_title">Хичээл</label>
                    {{ form.title }}
                    {{ form.title.errors }}
                </div>
                <div class="form-group">
                    <label for="id_content">Агуулга</label>
                    {{ form.content }}
                    {{ form.content.errors}}
                </div>
                <div class="form-group">
                    <label for="id_deadline">Дуусах хугацаа</label>
                    {{ form.deadline }}
                    {{ form.deadline.errors }}
                </div>
                <div class="form-group">
                    <label for="id_image">Зураг</label>
                    {{form.image}}
                    {{form.image.errors}}
                </div>
                <div class="form-group">
                    <label for="id_lesson">Хичээл сонгох</label>
                    {{form.lesson}}
                    {{form.lesson.errors}}
                </div>
               <div class="text-center">
                <br><button type="submit" class="btn btn-primary">Гэрийн даалгавар бүртгэх</button>
               </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

hello/templates/homework.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <h2>My homeworks</h2>
    <table class="table">
        <thread>
            <tr>
                <th></th>
                <th scope="col">Хичээл</th>
                <th scope="col">Агуулга</th>
                <th scope="col">Дуусах хуугацаа</th>
                <th scope="col">Нэмсэн огноо</th>
                <th scope="col">Зураг</th>
                <th scope="col">Хичээл</th>
                <th scope="col">Үйлдэл</th>
            </tr>
        </thread>
        <tbody>
        {% for homework in homeworks %}
        <tr>
            <td><input type="checkbox" {% if homework.done == True %}checked{% endif %}
                onclick="done(this, '{% url 'homework_done' homework.id %}')"
                /></td>
            <th scope="row">{{ homework.title }}</th>
            <td>{{ homework.content }}</td>
            <td>{{ homework.deadline }}</td>
            <td>{{ homework.created_date }}</td>
            <td>
                <img width="50%" src="{{MEDIA_URL}}{{homework.image}}">
           </td>
            <td>
                <a href="{% url 'homework_edit' homework.id %}">Засах</a>
                <a href="{% url 'homework_delete' homework.id%}" onclick="return confirm('Та устгахдаа итгэлтэй байна уу ?')">Устгах</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagintion">
        <span class="stop-links">
            {% if homework.has_previous %}
                <a href="?page=1">first</a>
                <a href="?page={{ homeworks.previous_page_number}}">previous</a>
            {% endif %}
            <span class="current">
                Page {{ homeworks.number }} of {{homeworks.paginator.run_pages}}
            </span>
            {% if homework.has_next %}
                <a href="?page={{ homeworks.next_page_number}}">next</a>
                <a href="?page={{ homeworks.paginator.run_pages}}">last</a>
            {% endif %}
        </span>
    </div>
</div>
<script>
    function done(target, url){
        if (target.checked == true){
            window.location = url + '?done=True'
        }else{
            window.location = url + '?done=False'
        }
    }
</script>
{% endblock %}+

hello/templates/register.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-xl-5 col-lg-6 col-md-10 col-sm-12 mx-auto mt-5">
        <h2> Бүртгүүлэх </h2>
        {% if message != '' %}
            <p class="alert alert success">{{ message}}</p>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="card body">
                <div class="form group">
                    <label for="id_username">хэрэглэгчийн нэр</label>
                    {{ form.username }}
                    {{ form.username.errors }}
                </div>
                <div class="form-group">
                    <label for="id_password">Нууц үг</label>
                    {{ form.password1 }}
                    {{ form.password1.errors }}
                </div>
                <div class="form-group">
                    <label for="id-password">Нууц үг давтан оруулна уу</label>
                    {{ form.password2 }}
                    {{ form.password2.errors }}
                </div>

                <div class="text-center">
                    <br><button class="btn btn-primary">Нэвтрэх</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}